"""second migration

Revision ID: 9d8daced8a89
Revises: f91a4189454d
Create Date: 2024-02-01 18:17:07.218732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d8daced8a89'
down_revision = 'f91a4189454d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('temperature')
        batch_op.drop_column('country')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=2), nullable=True))
        batch_op.add_column(sa.Column('temperature', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
